### ISSUE TITLE
option for comment from articles page

### ISSUE THREAD

**Issue by Rohan-cod** [Rohan-cod/newspaper-app#3]
Add an option to add comment to an article directly from the articles page. The model for comment is already built, just add a link to add comment.

**Comment by amancode27** [comment]
while saving  comment i am facing this error! 


Request Method: | POST
-- | --
http://127.0.0.1:8000/articles/1/comment/
3.0
IntegrityError
NOT NULL constraint failed: articles_comment.article_id
