### ISSUE TITLE
Adding navbar in profile page (frontend).

### ISSUE THREAD

**Issue by dollyjain51099** [Rohan-cod/newspaper-app#41]
Implementing navbar of the profile page (frontend) and making user profile more interactive.

**Comment by dollyjain51099** [comment]
I have created this issue and I want to work on this. Please assign this issue #41 to me.

**Comment by Rohan-cod** [comment]
There is a nav bar already in base.html. There is no need to implement a separate nav bar for the profile page. The issue can be like- enhancing the current nav bar. You can replace the bootstrap code with your own using css. 

This issue is not correct.
