### ISSUE TITLE
facing error while setting up the project

### ISSUE THREAD

**Issue by tusharnankani** [Rohan-cod/newspaper-app#47]
Hi, I am facing some errors while setting up the project locally.

![image](https://user-images.githubusercontent.com/61280281/103441427-faf14d00-4c73-11eb-9472-436a857dfff6.png)

It says: `Failed creating virtual environment`

**Comment by Rohan-cod** [comment]
There is no need to create an issue for that. You must ask your issues in the communication channel. You can join the slack channel using this [link](https://join.slack.com/t/codingninjas-talk/shared_invite/zt-k9sm2slj-1HEXKlxHBbxwviX5JvaCWw).
